import { Navbar } from '@/components/landing/Navbar';
import { Footer } from '@/components/landing/Footer';

export default function Disclaimer() {
  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="container mx-auto px-4 py-32 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
        
        <div className="prose prose-lg dark:prose-invert max-w-none space-y-6">
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
          
          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">AI-Generated Content</h2>
            <p className="text-muted-foreground">
              The content generated by ViralHook AI is created using artificial intelligence. While we strive to provide high-quality, relevant content suggestions, we cannot guarantee that all generated content will be suitable for your specific needs or audience.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">No Guarantee of Virality</h2>
            <p className="text-muted-foreground">
              The term "viral" is used to describe content optimized for engagement. We do not guarantee that content generated using our service will go viral or achieve any specific level of engagement on social media platforms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">User Responsibility</h2>
            <p className="text-muted-foreground">
              You are solely responsible for reviewing, editing, and ensuring the appropriateness of any content before publishing it on social media platforms. Always verify that generated content complies with platform guidelines and applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">Third-Party Platforms</h2>
            <p className="text-muted-foreground">
              ViralHook AI is not affiliated with Instagram, TikTok, YouTube, or any other social media platform. Each platform has its own terms of service and content guidelines that you must follow.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">Earnings Disclaimer</h2>
            <p className="text-muted-foreground">
              Any examples of results or earnings are not guarantees. Individual results will vary based on numerous factors including your niche, audience, consistency, and content quality.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mt-8 mb-4">Contact</h2>
            <p className="text-muted-foreground">
              If you have questions about this disclaimer or our services, please contact our support team.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
